<x-web.layout id="growthfundpage">

    @push('meta')
        <meta name="keywords" content="{{  __("cryptocurrency, funds, investment fund, crypto funds, mutual fund, directional, active, Growth Fund") }}">
        <meta name="description" content="{{  __("A directional investment fund with a target return of 45%. Diversified and safe investing in the fastgrowing crypto market.") }}">
    @endpush

    <x-slot:title>
        {{ __("Growth Fund | BlockchainTraders") }}
    </x-slot>
    
    <x-slot:heading>
        <div class="heading">
            <h1>BlockchainTraders Growth Fund</h1>

            <p class="subtitle">{{ __("Diversified and safe investing in the fastgrowing crypto market.") }}</p>
        </div>
    </x-slot>

    <section id="about_the_fund">
        <x-web.afm-banner />
        
        <h2>{{ __("About the fund") }}</h2>

        <p>{{ __("BlockchainTraders Growth Fund started in 2018. This fund benefits from the growth and mass adoption of blockchain by investing in cryptocurrencies. BlockchainTraders Fund A manages to achieve good returns in an emerging market with its proven strategy.") }}</p>

        <p>{{ __("Returns are generated by price gains on cryptocurrencies and by trading proceeds, making the fund in dominance a directional investment in cryptocurrencies. The return forecast is over 30% per annum with a 3-year investment horizon.") }}</p>

        <table class="fund_return_figures">
            <thead>
                <tr>
                    <th>{{ __("RETURN YTD") }}*</th>
                    <th>{{ __("ANNUALIZED RETURN") }}**</th>
                    <th>{{ __("HIGHER RETURN THAN THE MARKT") }}***</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>7%</td>
                    <td>27%</td>
                    <td>13%</td>
                </tr>
            </tbody>
        </table>
        {{-- <x:chart-js-fund-chart fund-identifier="3" euro-line-color="#2c82be" :multi-currency=false /> --}}

        <p><b>{{ __("Opportunity: taking advantage of a revolution") }}</b></p>

        <ul>
            <li>{!! __("<b>Unique access:</b> with the Growth Fund BlockchainTraders provides an opportunity for investors to take advantage of the revolutionary growth in blockchain technologies;") !!}</li>
            <li>{!! __("<b>BlockchainTraders</b> has in-depth experience and knowledge of this market and a proven track record in managing cryptocurrencies;") !!}</li>
            <li>{!! __("The <b>strength</b> of the investment strategy lies in the <b>active management</b> of cryptocurrency positions and trading activities in order to maximize returns and minimize risks.") !!}</li>
        </ul>

        <p><b>{{ __(" Riskmanagement: risk mitigation") }}</b></p>

        <p>{{ __("Risk management is crucial in the investment process, which focuses on generating the most stable returns possible and limiting downward movements in the long term. Risks are greatly mitigated by:") }}</p>

        <ul>
            <li>{!! __("To invest mainly in the <b>‘reputable'</b> cryptocurrencies with a <b>large market capitalization</b> in order to be as liquid as possible and to be able to switch quickly;") !!}</li>
            <li>{!! __("<b>Stop Losses</b> to break losses in time and use the money for other opportunities with better return potential;") !!}</li>
            <li>{!! __("<b>Continuous monitoring</b> and <b>reallocation</b> of crypto investments.") !!}</li>
        </ul>

        <p class="small">
            * {{ __("Return from December 31, 2023, to August 27, 2024.") }}
            <br>** {{ __("Since 28 January 2020; the start of the current strategy of BlockchainTaders Growth Fund.") }}
            <br>*** {{ __("CCI30 in EUR after costs, since 28 January 2020.") }}
            <br>1 {{ __("High Water Mark (HWM), and no hurdle rate applies.") }}
            <br>2 {{ __("'Other' refers to accounting costs, registration costs at the AFM.") }}
            <br>{{  __("No rights can be derived from the information on this page.") }}
        </p>

    </section>

    <section class="fund_info">
        <h3>{{ __("Investment information") }}</h3>
        <hr>
        <table>
            <tbody>
                <tr>
                    <th>{{ __("Fonds inception") }}</th>
                    <td>{{ __("17 august 2018") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Investment strategy") }}</th>
                    <td>{{ __("Crypto directional / active trading") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Lead Portfolio manager") }}</th>
                    <td>Justin Kool</td>
                </tr>
                <tr>
                    <th>{{ __("Co-Portfolio manager") }}</th>
                    <td>Michiel van der Steeg</td>
                </tr>
            </tbody>
        </table>
    </section>

    <section class="fund_info">
        <h3>{{ __("Fund information") }}</h3>
        <hr>
        <table>
            <tbody>
                <tr>
                    <th>{{ __("Legal structure") }}</th>
                    <td>{{ __("Mutual Fund") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Fiscal status") }}</th>
                    <td>{{ __("Untaxed") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Transferability") }}</th>
                    <td>{{ __("Non transferable") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Minimum participation") }}</th>
                    <td>€100.000</td>
                </tr>
                <tr>
                    <th>{{ __("Redemption Fee") }}</th>
                    <td>2% ({{ __("first year only") }})</td>
                </tr>
                <tr>
                    <th>{{ __("Withdrawals / Deposits") }}</th>
                    <td>{{ __("Monthly") }}</td>
                </tr>
            </tbody>
        </table>
    </section>

    <section class="fund_info">
        <h3>{{ __("Cost structure") }}</h3>
        <hr>
        <table>
            <tbody>
                <tr>
                    <th>{{ __("Start-up costs") }}</th>
                    <td>{{ __("€845 (one-time)") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Management fee") }}</th>
                    <td>{{ __("0,4% (quarterly)") }}</td>
                </tr>
                <tr>
                    <th>{{ __("Performance fee") }}</th>
                    <td>{{ __("15% (lifelong HWM)") }}<sup>1</sup></td>
                </tr>
                <tr>
                    <th>{{ __("Other costs") }}</th>
                    <td>1% <sup>2</sup></td>
                </tr>
            </tbody>
        </table>
    </section>

    <section class="fund_info">
        <h3>{{ __("Service providers") }}</h3>
        <hr>
        <table>
            <tbody>
                <tr>
                    <th>{{ __("Investment manager") }}</th>
                    <td>BlockchainTraders B.V.</td>
                </tr>
                <tr>
                    <th>{{ __("Judicial owner ") }}</th>
                    <td>Stichting Toezicht<br>BlockchainTraders</td>
                </tr>
                <tr>
                    <th>{{ __("Bank") }}</th>
                    <td>Bunq B.V.</td>
                </tr>
                <tr>
                    <th>{{ __("Custodial solution") }}</th>
                    <td>Fireblocks</td>
                </tr>
                <tr>
                    <th>Corporate Exchange</th>
                    <td>Bitvavo / Flow Traders </td>
                </tr>
                <tr>
                    <th>KYC Software</th>
                    <td>ComplianceWise</td>
                </tr>
                <tr>
                    <th>Wwft Internal Auditor</th>
                    <td>Endymion</td>
                </tr>
            </tbody>
        </table>
    </section>

    <section class="fund_info documentation">
        <h3>{{ __("Fund documentation") }} Growth Fund</h3>
        <hr>
        <table>
            <tbody>
                <tr>
                    <th><i class="fa-solid fa-file-lines"></i> {{ __("Essential information document") }}</th>
                    <td onclick="openInformationRequestModal('Growth Fund Essential information document')" class="link">{{ __("Request") }} <i class="fa fa-arrow-right fa-fw"></i></td>
                </tr>
                <tr>
                    <th><i class="fa-solid fa-file-lines"></i> {{ __("Information Memorandum") }}</th>
                    <td onclick="openInformationRequestModal('Growth Fund Information Memorandum')" class="link">{{ __("Request") }} <i class="fa fa-arrow-right fa-fw"></i></td>
                </tr>
                <tr>
                    <th><i class="fa-solid fa-file-lines"></i> {{ __("Performance update") }}</th>
                    <td onclick="openInformationRequestModal('Growth Fund Performance update')" class="link">{{ __("Request") }} <i class="fa fa-arrow-right fa-fw"></i></td>
                </tr>
                <tr>
                    <th><i class="fa-solid fa-file-lines"></i> {{ __("Product Information document") }}</th>
                    <td onclick="openInformationRequestModal('Growth Fund Product Information document')" class="link">{{ __("Request") }} <i class="fa fa-arrow-right fa-fw"></i></td>
                </tr>
            </tbody>
        </table>
    </section>

</x-web.layout>